version: '3'

services:
  web_nginx:
    image: nginx
    container_name: web_nginx
    volumes:
      - ./nginx/app.conf:/etc/nginx/nginx.conf
      - ./nginx/app2.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - app_nodejs

  db_postgres:
    image: postgres
    container_name: db_postgres
    restart: always
    environment:
      - POSTGRES_USER:postgres
      - POSTGRES_PASSWORD:masterkey
    ports:
      - 5432:5432
    volumes:
      - vol-db-postgres:/var/lib/postgresql/data

  app_nodejs:
    image: lutzmatos/app-ngnix-node-postgres-tasks
    container_name: app_nodejs
    build: .
    ports:
      - 3090
    depends_on:
      - db_postgres

volumes:
  vol-db-postgres: 